styles-screen
css25AutocompleteField
^'
div.auto_complete {
      position:absolute;
      width:350px;
	background-color: #fff
}
div.auto_complete ul {
	border:1px solid #888;
	background-color: #fff;
	margin:0;
	padding:0;
	width:100%;
	list-style-type:none;
}
div.auto_complete ul li {
	margin:0;
	padding:3px;
}
div.auto_complete ul li.selected { 
	background-color: #ffb; 
}
div.auto_complete ul strong.highlight { 
	color: #800; 
	margin:0;
	padding:0;
}
'