styles-screen
css24WebGrid
	^'
table.webGrid {
	border: 1px solid #E4E4E4;
	border-collapse: collapse;
	margin-bottom: 4px;
	font-size: 12px;
	color: #484849;
	background-color: #FFFFFF;
}
table.webGrid tr {}
table.webGrid td {border-top: 1px solid #F8F8F8;}
table.webGrid td input {font-size: 9pt;}

table.webGrid tbody tr:hover {background-color:#ffffdd;}

table.webGrid th {
	padding: 4px; 
	background: #EEEEEE;
}
table.webGrid th a {color: #2A5685;}
table.webGrid th a:hover {color: #C61A1A;}

table.webGrid tr.red td, tr.red a { color: red; }
table.webGrid tr.green td, tr.green a { color: forestgreen; }
table.webGrid tr.blue td, tr.blue a { color: blue; }
table.webGrid tr.yellow td, tr.yellow a { color: yellow; }
table.webGrid tr.gray td, tr.gray a { color: darkgray; }
table.webGrid tr.summary td, tr.summary a { color: darkgray; font-weight: bold }
'