styles-screen
css3Header
^'
#banner {
	height: 0px;
	width: 780px;
	margin: 0 0px 0px 0px; 
	padding: 0px 0; 
	background: #fff;
	text-align: center;
	white-space: nowrap;
	}
#banner div {
	padding: 0;
	border-bottom: none;
	}
#header {
	height: 95px;
	width: 780px;
	border: none;
	}
#logo {
	height: 95px;
	position: absolute;
	top: 2px;
	left: 5px;
	right: auto;
	color: #fff;
	white-space: nowrap;
	z-index: 1000;
	}
#dashboard {
	height: 24px;
	width: 780px;
	margin: 4px 0;
	line-height: 23px;
	font-size: 10px;
	background: #F0F0E7 url(/img/cornerdashboardleftGif.gif) no-repeat;
	color: #666;
	}
#switcher {
	position: absolute; 
	vertical-align: middle;
	top: 102px;
	right: 45px;
	margin: 0;
/*	z-index: 1001; */
	}
#switcher a b { position: relative; bottom: 4px; right: 10px}
#switcher a img {
	background: #999;
	}
#switcher a:hover img {
	background: #000;
	}

'