styles-mobile
cssMobile23Inputs
^'
fieldset { }
fieldset td { }
legend { font-size: 100%; }
form { }
input, button {
	font-size: 120%;
	padding: 7px; spacing: 2px;
	padding-left: 3px; padding-right: 3px;
	spacing-left: 0px; spacing-right: 0px;
}
textarea { font-size: 100%; }
select {
	font-size: 110%;
	padding: 7px; spacing: 2px;
	padding-left: 3px; padding-right: 3px;
	spacing-left: 0px; spacing-right: 0px;
}
'